.TH SERVER 1 "23 November 23"

.SH NAME
server \- server for Tands funcs
.SH SYNOPSIS
\fBserver\fP \fIport\fP
.SH DESCRIPTION
\fBserver\fP starts a server on \fIport\fP which
will be capable of executing transactions and
saving a history and summary in Summary log file.
.SH FILES
.TP
\fC./Server\fR
the server log file
.SH "SEE ALSO"
client(1)
.SH BUGS
if client supplies incorrect transaction
or if server called with incorrect arguments
then program crashes.